version: "3"

services:
  bot:
    build: .
    restart: unless-stopped
    container_name: eu-electricity-tomorrow-bot
    volumes:
      - data:/bot-data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
    - ./env_file
    tty: true
volumes:
  data: